7-umc-GrowIT/GrowIT-SpringBoot

build.gradle, src/main/java/umc/GrowIT/Server/config/SwaggerConfig.java
> Swagger 설정 완료
> 1. http://localhost:8080/swagger-ui/index.html 접속
>  ![image](https://github.com/user-attachments/assets/8eb078c1-8927-43c7-8ada-3e1d83c68e1c)
=> [#1] Chore: Swagger 설정

src/main/java/umc/GrowIT/Server/web/controller/DiaryRestController.java, src/main/java/umc/GrowIT/Server/web/dto/DiaryRequestDTO.java, src/main/java/umc/GrowIT/Server/web/dto/DiaryResponseDTO.java
> 일기 관련 API 명세서 작성하였습니다(Swagger)
=> [#16] Feat: 일기 관련 API 명세서 작성

src/main/java/umc/GrowIT/Server/converter/ItemConverter.java, src/main/java/umc/GrowIT/Server/domain/Item.java, src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java, src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryCustom.java, src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepositoryImpl.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryService.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java, src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
=> [#19] Feat : 카테고리별 아이템 조회 API기능 구현

src/main/java/umc/GrowIT/Server/domain/Diary.java, src/main/java/umc/GrowIT/Server/web/controller/DiaryRestController.java, src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java, src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
> 일기관련된 부분에서 제목부분을 제거하고 관련된 부분을 수정하였습니다.
> 변경된 부분에 이상 없는지만 확인해주세요.
=> [#27] Refactor: 일기 제목부분 제거 및 수정

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java, src/main/java/umc/GrowIT/Server/domain/Challenge.java, src/main/java/umc/GrowIT/Server/domain/ChallengeKeyword.java, src/main/java/umc/GrowIT/Server/domain/Diary.java, src/main/java/umc/GrowIT/Server/domain/Keyword.java, src/main/java/umc/GrowIT/Server/domain/UserChallenge.java, src/main/java/umc/GrowIT/Server/domain/enums/ChallengeStatus.java, src/main/java/umc/GrowIT/Server/domain/enums/ChallengeType.java, src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java, src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java, src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java, src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java, src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java, src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
> 챌린지 홈을 조회하는 API입니다.
회원가입을 진행하고 크레딧과 일기를 추가해야 정상적으로 조회됩니다.
(recommendedChallenges는 아직 출력되지 않음.)
> ![image](https://github.com/user-attachments/assets/7aa40b58-1b17-4742-8f29-97752c3cb58d)
=> [#30] Feat: 챌린지 홈 조회 API 개발

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/GrowIT/Server/web/controller/GroController.java, src/main/java/umc/GrowIT/Server/web/controller/ItemController.java, src/main/java/umc/GrowIT/Server/web/controller/UserController.java, src/main/java/umc/GrowIT/Server/web/controller/specification/GroSpecification.java, src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java, src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
Item, Gro, User Controller에 속한 API일부에 대한 Specification파일 작성 및  Controller파일 코드 간소화
=> [#45] Feat : Item, Gro, User Controller에 속한 API일부에 대한 Specification파일 작성

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java, src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
> 일기 관련 API의 Specification을 작성하였습니다.
> 1. 실행결과에 변화는 없으므로 실행 후 Diary부분이 이상이 없는지만 확인해주세요.
=> [#54] Refactor: 일기 관련 API의 Specification 작성

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java, src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java, src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java, src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java, src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
=> [#113] Feat: 일기 삭제 API 구현

src/main/java/umc/GrowIT/Server/domain/Term.java, src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java, src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
테스트용
> 1. <테스트 방법을 상세히 적어주세요 (스크린샷 첨부 가능)>
=> [#115] Feat: CI/CD 테스트

.github/workflows/dev_deploy.yml
=> [#133] Bug : 업로드 artifact버전 변경

src/main/java/umc/GrowIT/Server/config/SecurityConfig.java, src/main/java/umc/GrowIT/Server/config/WebConfig.java, src/main/java/umc/GrowIT/Server/jwt/CustomAuthenticationEntryPoint.java
1. CORS 설정
2. CORS 설정 테스트 하다가 널 포인터 예외 발생했는데 우선 BAD_REQUEST 로 지정했습니다.
http://localhost:3000 에서 개발자 도구 콘솔에 다음과 같이 입력
- CORS 정책에 의해 요청 거부
- 요청 성공
*localhost:8080 으로 요청했는데, develop 에 CORS 설정 적용되면 아마 현재 서버 주소로도 요청 가능할 것 같습니다.
=> [#140] CORS 설정

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/GrowIT/Server/converter/ItemConverter.java, src/main/java/umc/GrowIT/Server/domain/Item.java, src/main/java/umc/GrowIT/Server/domain/UserItem.java, src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java, src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/web/controller/ItemController.java, src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java, src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipRequestDTO.java
> 그로의 아이템 착용상태를 바꾸는 api를 구현했습니다.
> ios요청사항을 반영해 그로 착용에 사용할 이미지 key를 저장하기위해 item 엔티티에 변수 추가를 했습니다.
- 파라미터에 아이템 Id를 넣고 status에 현재 착용상태를 입력합니다. (착용상태 > EQUIPPED | 미착용상태 > UNEQIPPED)
- 현재 착용상태와 일치하지않는 status를 보내면 에러
=> [#129] Feat : 그로 아이템 착용/해제 api & 아이템 착용용 이미지기능 추가

src/main/java/umc/GrowIT/Server/web/dto/OAuthDTO/OAuthResponseDTO.java
application.yml 프론트에서 인가코드 얻어오는 redirect-uri 로 수정
=> [#156] Fix: application.yml redirect-uri 수정

src/main/java/umc/GrowIT/Server/service/oAuthService/kakaoService/KakaoServiceImpl.java
application.yml 에서 redirect-url 뿐만 아니라 client-id 도 수정이 필요하다고 하여 수정했습니다..
=> [#156] Fix: 카카오 로그인 API IOS 연동

src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/web/dto/OpenAIDTO/ChatGPTRequest.java, src/main/java/umc/GrowIT/Server/web/dto/OpenAIDTO/Message.java
> 1. 파인튜닝을 진행한 AI를 적용시켰습니다.
> - 직접 대화해보시고 더 개선이 필요할 것 같으면 말해주세요.
> - 사용한 데이터셋은 개발문서에 올려놓도록 하겠습니다.
> 1. 파인튜닝 AI와 대화 - 요약 흐름
> 대화를 이어가려면 diaries/voice 요청을 계속 보내고 대화 종료시에 diaries/summary 요청을 보내시면 됩니다.
> 여기까지 대화하고 요약
=> [#167] Feat: 파인튜닝 AI 적용

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/GrowIT/Server/repository/GroRepository/GroRepository.java, src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java, src/test/resources/application.yml
> 그로를 생성할 때 PLANT가 "핑크 화분"으로 설정되게 하였습니다
> 그로 생성 API 테스트 중 그로가 이미 존재하는 경우에 대한 예외처리가 안된 것을 발견하여 에러처리 추가했습니다.
> 이미 그로가 있는 사용자가 그로 생성하려고 하는 경우
=> [#184] Refactor : 기본PLANT 변경 및 그로 예외처리

src/main/java/umc/GrowIT/Server/domain/Term.java, src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
> DB가 정리됨에 따라 일기 분석 요청 프롬프트에 DB 내용을 넘기도록 코드 수정하였습니다.
> Term의 content는 버그로 인해 임시로 수정하였습니다. 서영님 PR 올리신거 결과에 따라 재수정하겠습니다.
> 
> ‼️ 문제 ‼️
> 프롬프트에서 DB의 감정들을 참조하게 되며, 잘 작동하는지를 체크해봤습니다.
> 2가지 문제가 있습니다.
> 1) DB에 없는 감정을 반환하여 오류 발생
> 기존에 제가 사용하던 일기 내용+임시로 감정키워드 5개일 때는 다행히도 발생하지 않았던 오류였습니다.
> 그런데, 다른 내용+DB 감정키워드 참조로 코드를 변경하였더니 조금 높은 확률로 해당 오류가 발생합니다.
> 프롬프트를 변경하였으나, 대책이 필요할 거 같습니다..
> ![image](https://github.com/user-attachments/assets/fa3539e5-d033-4625-8789-47924887cdd6)
> ![image](https://github.com/user-attachments/assets/f47d18ef-2dc1-49e8-b41b-6f7ec67e905f)
> ![image](https://github.com/user-attachments/assets/b85a17d9-fa9f-43c3-bdb2-d4178f913657)
> 2) 잘못된 감정 분석
> 1)의 오류가 발생하지 않더라도, 일기 내용과 관련없는 키워드가 반환됩니다.
> 제가 테스트했을 때에는 아래 내용과 관계없는 `행복한`이라는 키워드가 반환되었습니다.
> [테스트에 사용한 일기 내용]
> `어쩐지 오늘은 더 피곤한 삳태로 …
=> [#192] Refactor: 일기 분석 API 수정

src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
> 일기 요약 시에 gpt-3.5-turbo 모델일때는 없었던 문제가 gpt-4o-mini 모델로 변경되면서 임의의 날짜를 일기에 삽입하는 문제가 발생되어 이를 해결하기 위해 프롬프트를 변경하였습니다.
> x
=> [#202] Fix: 음성 일기, 일기 요약 API 프롬프트 수정

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java, src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
> 오늘의 일기가 아니어도 감정분석과 챌린지 추천이 가능하도록 변경하였습니다.
> x
=> [#206] Fix: 날짜 검사 부분 제거

src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java, src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
> 아이템 착용시에 해당 아이템과 카테고리가 같은 아이템 중 status가 EQUIPPED인 아이템이 해제처리되게 수정했습니다
> x
=> [#220] Refactor : 아이템 착용시 기존 아이템 착용해제처리로직 추가

build.gradle, src/main/java/umc/GrowIT/Server/config/WebConfig.java, src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
> Swagger 에서 API 테스트 시 CORS 오류로 인해 설정 수정
설정에서 허용할 HTTP 메소드에 PATCH 가 빠져있어서 추가했습니다.
추가) AWS SDK 버전으로 인해 실행 시 경고가 떠서 확인이 필요할 것 같습니다 @sehyeo 님이 확인부탁드립니다~!
> 1. <테스트 방법을 상세히 적어주세요 (스크린샷 첨부 가능)>
=> [#277] Bug : CORS 설정 수정

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
파일 경로가 이동되면서 임포트문에서 에러 발생(`CreditDTO`)
1.
=> [#303] Fix: 파일 경로에 따른 불필요한 임포트문 삭제

src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
=> [#308] Setting : 토큰 만료 시간 임시 변경

.gitignore, src/main/resources/logback-spring.xml
1. .gitignore 파일에 로깅관련 파일들을 추가했습니다
2. 로깅 설정파일 `logback-spring.xml`을 추가하였습니다.
https://www.notion.so/26019677ed4280ca9f6df5bcc2c14ddf
1. 개발활경
```cmd
.\gradlew bootRun --args='--spring.profiles.active=dev'
```
| 콘솔에만 로그 출력
2. 배포환경
```cmd
.\gradlew bootRun --args='--spring.profiles.active=prod'
```
- logs 폴더 생성
- growit-all.log - 모든 로그 기록
- growit-error.log - 에러 로그만 기록
=> Setting/#285 서버 로그 기록 세팅

src/main/java/umc/GrowIT/Server/apiPayload/code/ReasonDTO.java, src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
1. 애플 로그인 appliction-dev 랑 application-prod의 client id 일치하지 않아서 오류 발생해서 해당 부분 수정
2. 프론트 요청으로 토큰 만료시간 변경
1.
=> [#315] Setting : apple client id 수정 및 토큰 만료 시간 임시 설정

src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
AT RT 같은 시간으로 인해 AT 재발급 테스트 불가
RT 1분->5분
1.
=> [#320] Setting : 토큰 만료시간 임시 재변경

src/main/java/umc/GrowIT/Server/converter/OAuthConverter.java, src/main/java/umc/GrowIT/Server/domain/OAuthAccount.java, src/main/java/umc/GrowIT/Server/service/oAuthService/appleService/AppleServiceImpl.java, src/main/java/umc/GrowIT/Server/service/oAuthService/kakaoService/KakaoServiceImpl.java, src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java, src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthResponseDTO.java, src/main/java/umc/GrowIT/Server/web/dto/OAuthDTO/OAuthApiResponseDTO.java, src/main/java/umc/GrowIT/Server/web/dto/OAuthDTO/OAuthRequestDTO.java, src/main/java/umc/GrowIT/Server/web/dto/OAuthDTO/OAuthResponseDTO.java
application.yml
client id web용으로 되어있던 부분 app으로 수정
추가 ) dto 널값일 때 응답에 포함시키지 않았는데
포함되고 안 됨에 따라 응답이 많이 달라져서
프론트에서 처리하기 어려울 것 같아 포함시키도록 했습니다.
1.
=> [#323] Bug : 애플 로그인 Client 설정 오류

src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
기존 코드 주석처리 해제하여 
엑세스 -> 1시간
리프레시 -> 60일
원상복구합니다
1.
=> [#335] Refactor : 엑세스&리프레시 토큰 수명 수정

src/main/java/umc/GrowIT/Server/config/SecurityConfig.java, src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
애플 로그인 관련 응답을 로컬에서 받을 수 없어서
서버에서 응답 오는 거 테스트로 확인하고 작업하고 다시 원상복구 해놓겠습니다!
1.
=> [#338] Chore : 애플 로그인 테스트

src/main/java/umc/GrowIT/Server/util/JwtTokenUtil.java
- 기존 만료시간 주석 처리
- 임시 만료시간 설정 (3분/30분)
X
X
=> [#347] Setting: AT&RT 만료시간 임시 변경

src/main/java/umc/GrowIT/Server/service/oAuthService/OAuthCommandServiceImpl.java, src/main/java/umc/GrowIT/Server/service/oAuthService/appleService/AppleServiceImpl.java
소셜간편가입 시 social id 가 null로 넘어오는 것 같은데
로컬 테스트 어려워서 로그 추가했습니다
1.
=> [#335] Bug : 소셜 간편가입 오류로 로그 추가

src/main/java/umc/GrowIT/Server/repository/ItemRepository.java, src/main/java/umc/GrowIT/Server/service/itemService/ItemQueryServiceImpl.java
카테고리별 아이템 조회 시 가격 오름차순 정렬 작업하였음.
x
1. 수정 전
2. 수정 후
=> [#394] Refactor: 카테고리별 아이템 조회 시 가격 오름차순 정렬

src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
긴 대화용 - 짧은 대화용 모델이 서로 바껴있었습니다.... 
1.
=> [#401] Refactor : 일기 요약 gpt 모델 교체

src/main/java/umc/GrowIT/Server/config/WebConfig.java
=> [#420] Setting : CORS 설정 추가
