build.gradle

> springdoc-openapi 버전 2.7.0으로 변경
> 1. http://localhost:8080/swagger-ui/index.html 접속
> ![image](https://github.com/user-attachments/assets/b51f7d32-32d9-4269-853d-bb4c77ee0876)

[#8] Fix: Swagger 버전 변경

---

build.gradle
src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/domain/Gro.java
src/main/java/umc/GrowIT/Server/domain/Item.java
src/main/java/umc/GrowIT/Server/domain/RefreshToken.java
src/main/java/umc/GrowIT/Server/domain/Term.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/domain/UserItem.java
src/main/java/umc/GrowIT/Server/domain/UserTerm.java
src/main/java/umc/GrowIT/Server/domain/common/BaseEntity.java
src/main/java/umc/GrowIT/Server/domain/enums/ItemCategory.java
src/main/java/umc/GrowIT/Server/domain/enums/ItemStatus.java
src/main/java/umc/GrowIT/Server/domain/enums/Provider.java
src/main/java/umc/GrowIT/Server/domain/enums/TermType.java
src/main/java/umc/GrowIT/Server/domain/enums/UserStatus.java
src/main/java/umc/GrowIT/Server/web/controller/GroController.java
src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/dto/CreditDTO/CreditResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemEquipDTO/ItemEquipResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/PaymentDTO/PaymentRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/PaymentDTO/PaymentResponseDTO.java

--------
- domain
- Gro
- Item
- RefreshToken
- UserItem
- web
- controller
-  GroController
- ItemController
- UserController
- dto
- CreditDTO
- GroDTO
- ItemDTO
- ItemEquipDTO
- PaymentDTO

[#7] Feat: 아이템/Gro관련 Entity 및 API Swagger관련기능 생성

---

src/main/java/umc/GrowIT/Server/controller/User2Controller.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java
src/main/java/umc/GrowIT/Server/web/controller/HomeRestController.java
src/main/java/umc/GrowIT/Server/web/controller/ItemRestController.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/controller/UserRestController.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/HomeDTO/HomeResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java

> 아이템 구매/설정 API
> - 보유 중인 아이템 조회
> - 인증 메일 전송
> - 인증 번호 확인
> - 비밀번호 재설정
> - 회원 탈퇴
> - 아이템 구매
> - 홈 화면
> - 챌린지 삭제
> 1. 다른 이슈에서의 작업으로 인해 application.yml 업데이트 필요
> 2. http://localhost:8080/swagger-ui/index.html 접속
> <img width="1001" alt="image" src="https://github.com/user-attachments/assets/156810c1-b4a2-4a29-ae05-8225f5aa2b52" />

[#14] Feat: 아이템 구매/설정 관련 API

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/Challenge.java
src/main/java/umc/GrowIT/Server/domain/enums/ChallengeType.java
src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeRestController.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

>
(랜덤 챌린지, 데일리 챌린지 조회 API 곧 개발하겠습니다!)
> 챌린지 현황을 조회하는 API입니다. 먼저 스웨거에서 회원가입 후 Authorize에서 토큰 적용하셔야 합니다. 챌린지 테이블에 테스트 값들 넣어놨습니다. (챌린지 추천 기능은 API 또는 DB에 저장하는 식으로 구현할 예정)
completed에 true 값을 주면 완료한 챌린지가 조회되어야 하고, false 값을 주면 미완료한 챌린지가 조회되어야 정상입니다. 궁금하신 점 있으시면 커멘트 남겨주세요!!
completed가 테이블에서 bit형으로 선언되어있는데 completed가 0이면 false(미완료), completed가 1이면 true(완료)입니다. DB에 insert하실 때 참고해주세요!
(boolean형이 아닌 enum 등을 사용하여 수정해볼 예정 -> 아이디어 있으시면 답변 부탁드립니더..)
> 1. userId를 입력하고 completed에 아무런 값을 주지 않으면 전체 챌린지 조회
2. userId를 입력하고 completed에 true 값을 주면 완료한 챌린지 조회
3. userId를 입력하고 completed에 false 값을 주면 미완료한 챌린지 조회

[#33] Feat: 챌린지 현황 조회(완료/미완료) API 구현

---

src/main/java/umc/GrowIT/Server/converter/TokenConverter.java
src/main/java/umc/GrowIT/Server/domain/RefreshToken.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/service/refreshToken/RefreshTokenCommandService.java
src/main/java/umc/GrowIT/Server/service/refreshToken/RefreshTokenCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java

- user, refresh token 이 현재 1:1 관계, user가 연관관계 주인으로 설정한 상황입니다.
- 회원가입 API 에서 회원 email, name, password, userTerms 데이터 넣고 요청했을 때
user 테이블에 refresh token id 값(외래키)이 들어가지 않는 것을 확인 후 수정했습니다.
1. 스웨거에서 회원가입 요청
2. DB에 refresh token id (외래키) 들어가는지 확인

[#41] Bug : 회원가입 API Refresh token

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/Challenge.java
src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

> 챌린지 현황 중 랜덤챌린지와 데일리챌린지를 조회하는 API입니다.
챌린지를 조회하면 status값이 출력되는데, 화면설계서를 보면 "전체" 카테고리가 미완료 챌린지를 의미하기 때문에 미완료 챌린지를 조회하면 status="TOTAL"이라고 뜨고 완료 챌린지를 조회하면 status="COMPLETED"이라고 뜹니다.
- 미완료 챌린지 중 랜덤챌린지와 데일리챌린지는 status 값이 각각 RANDOM, DAILY로 출력됩니다.
- DB에 챌린지 값이 있어야 스웨거에서 테스트 가능(미완료, 완료, 랜덤, 데일리 모두 추가해야 테스트하기 굿굿)
- 저는 로컬호스트에서 테스트했지만 **RDS에서 테스트하려면 현재 Challenge 테이블에 dtype 값이 잘못 들어가있어서
yml파일에서 테이블 생성하고 DB에 값 insert하고 테스트 해야할겁니다!**
- (예시) Challenge 테이블
- (예시) UserChallenge 테이블
ChallengeType 값을 RANDOM, DAILY로 수정하였으며 Challenge 엔티티의
@Enumerated(EnumType.STRING)
private ChallengeType dtype;
코드에서@Column(nullable = false)
코드를 삭제하였습니다.    -> (결과) Challenge 테이블 dtype가 not null에서 null로 변경됨.
(dtype 값이 2가지이며, 카테고리는 총 4개이기 때문에 dtype 값을 줄 필요 없이 completed에 0 또는 1을 주면 미완료챌린지와 완료챌린지를 구분할 수 있게 구현함.)
텍스트로 설명하려니까 어렵네요 …

[#38] Feat: 챌린지 현황(랜덤, 데일리) 조회 API 구현

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java

> 아래의 화면에서 사용할 YY년MM월에 작성한 일기의 날짜들을 조회하는 API를 구현하였습니다.
> 1. 아래의 SQL문으로 데이터 삽입
```
insert into diary(id, created_at, updated_at, content, user_id) values
(1, '2025-1-16 22:13:00', '2025-1-16 22:13:00', '유저1의 1월 첫번째 일기', 1),
(2, '2025-1-17 22:13:00', '2025-1-17 22:13:00', '유저1의 1월 두번째 일기', 1),
(3, '2025-1-18 22:13:00', '2025-1-18 22:13:00', '유저1의 1월 세번째 일기', 1),
(4, '2025-1-18 22:13:00', '2025-1-18 22:13:00', '유저2의 1월 첫번째 일기', 2),
(5, '2024-12-31 22:13:00', '2024-12-31 22:13:00', '유저 1의 12월 첫번째 일기', 1);
insert into user(id,created_at, updated_at, current_credit, email, name, password) values
(1, NOW(), NOW(), 0, 'email', '유저1', 'pw'),
(2, NOW(), NOW(), 0, 'email2', '유저2', 'pw');
```
-  유저의 정보는 임시로 userId를 1을 받도록 구현해놓았습니다.
> 2. 프로그램 실행 후 year와 month 입력 후 결과 확인
2-1. 2023년 1월 조회 결과 없음
2-2. …

[#56] Feat: 일기 작성 날짜 조회 API 구현

---

src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java

이메일 회원가입 할 때 이메일 인증을 먼저 했는지 확인하는 코드 추가했습니다.
- 프론트에서 요청을 보낼 때 이메일 인증 여부를 보내게 됩니다.
- 회원가입 API 호출 시 이메일 인증 여부에 따라 인증 확인이 됐을 때 회원 정보를 등록하게 됩니다. 이메일 인증 확인이 되지 않았을 때 예외처리를 했습니다.
1. 회원가입 시 isVerified 에 false 값을 주면
2. 회원 등록에 실패합니다.

[#51] Feat: 회원가입 API 이메일 인증 확인

---

src/main/java/umc/GrowIT/Server/converter/UserConverter.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/service/userService/UserCommandService.java
src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java

> soft delete로 회원탈퇴 API를 만들었습니다
> - RequestDTO 삭제
> 피그마를 살펴보면 회원탈퇴 UI가 없으며 회원탈퇴는 우선도가 낮을 것이라 생각하여 기존에 생성해 두었던 탈퇴사유를 적는 RequsetDTO를 삭제하였습니다
> - 에러코드와 핸들러는 기존에 구현되어있는 것을 재사용하였으며, 이외 회원탈퇴와 관련하여 controller, service, converter 부분의 코드를 작성하였습니다
> 1. 탈퇴 테스트만을 위한 레코드를 RDS에 추가하였습니다
> (Datagrip UI로는 넣어졌는데 쿼리문으로 해보니 오류가 있어 UserId 16인 레코드 ACTIVE로 변경하여서 테스트하면 될 거 같습니다)
> 2. 실행 결과
>
> (a) 일반적인 경우
> 사용자 ID는 위의 쿼리문으로 생성된 ID로 임시 하드코딩되어 있습니다. 필요한 response형식이 명확하지 않아 탈퇴한 사용자의 name과 message를 전달하도록 하였습니다. 
> ![image](https://github.com/user-attachments/assets/5ad30117-5628-4672-bbbd-c65f738772e2)
> ![image](https://github.com/user-attachments/assets/c86bf48b-ace6-4292-8f21-bbe19af86d8d)
> (b) 탈퇴한 회원의 ID가 전달된 경우
> 이미 탈퇴한 회원인지를 체크하고 오류를 발생시킵니다
> ![image](https://github.com/user-attachments/assets/253ce17c-f125-48 …

[#50] Feat: 회원탈퇴 API 개발

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/ChallengeHandler.java
src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

> 특정 사용자의 특정 챌린지를 삭제하는 API입니다
> (추가적으로 챌린지에도 specification을 적용시켰습니다)
> 1. RDS user_challenge에 예외를 위한 레코드는 이미 존재합니다
> 정상 작동을 테스트하기 위해서는 아래 쿼리문만 실행하면 됩니다
> ```INSERT INTO `growit-dev-db`.user_challenge (completed, challenge_id, created_at, updated_at, user_id, thoughts, certification_image, status) VALUES (false, 4, null, null, 1, null, null, null)```
> <img width="945" alt="스크린샷 2025-01-18 오후 11 21 27" src="https://github.com/user-attachments/assets/61953898-a3ce-48a9-9462-6e6ecc288d9d" /><br>
>
> 2. 실행 결과
> 
> (a) 사용자의 ID가 잘못된 경우 (현재 임시로 1L로 하드코딩되어 있습니다)
> 사용자 챌린지 6번은 5번 user의 챌린지이기 때문에 오류가 발생합니다
> <img src="https://github.com/user-attachments/assets/1dc1460e-c85b-4bb7-b4fd-f45471587b19" alt="image">
> (b) 완료된 챌린지를 삭제하려는 경우
> 미완료한 챌린지만 삭제가 가능한 것으로 알고 있습니다. 프론트엔드에서 값이 잘못 전달되는 경우가 …

[#49] Feat: 챌린지 삭제 API 개발

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/ItemHandler.java
src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/domain/UserItem.java
src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandService.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ItemSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java

> 아이템 구매 API를 개발하였습니다
> - API와 관련한 controller, service, repository, converter 등의 코드를 작성하였습니다
> - 아이템 '구매'이기 때문에 엔드포인트 등을 order에서 purchase로 변경하였습니다
> 1. 아이템 구매 테스트를 위해 RDS에 UserId 17인 레코드를 추가하였습니다
> current_credit을 변경해가며 테스트하면 됩니다
> ![image](https://github.com/user-attachments/assets/e761b36a-79b8-4edb-a138-6635472a8f71)
> 2. 실행결과
> (a) 일반적인 경우
> 사용자 ID는 하드코딩하였으며, path-variable로 아이템 ID를 넘기면 보유 중인 크레딧과 아이템의 가격을 비교하여 구매를 진행합니다
> ![image](https://github.com/user-attachments/assets/a3cdb7cf-1380-43b5-8cb9-50e1c8838715)
> ![image](https://github.com/user-attachments/assets/89ff1ddd-60c7-4ca7-8ba5-aa6c8c3632f4)
> ![image](https://github.com/user-attachments/assets/c68f31ef-798d-439b-8f5b-32961a634510)
> (b) 보유 중인 아이템을 구매하려는 경우
> ![image](https://github.com/user-attachments/assets/809594b1-ff71-4b …

[#62] Feat: 아이템 구매 API 개발

---

src/main/java/umc/GrowIT/Server/apiPayload/exception/DiaryHandler.java
src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

> 아래의 화면에서 사용할 YY년MM월에 작성한 일기들을 조회하는 API를 구현하였습니다.
> 1. RDS에 필요한 데이터들을 삽입하였습니다.
> 유저의 정보는 임시로 userId를 2를 받도록 구현해놓았습니다.
>
> 1-1. diary 테이블
> <img width="680" alt="image" src="https://github.com/user-attachments/assets/4f797156-130c-4fe3-97d2-9e4223865a4e" />
>
> 1-2. user 테이블
> <img width="848" alt="image" src="https://github.com/user-attachments/assets/8f8066c0-fa69-4e28-b0dd-0a0f2ed1b7a8" />
>
>
> 2. 프로그램 실행 후 year와 month 입력 후 결과 확인
>
> 2-1. 2023년 1월 조회 결과 없음
> <img width="797" alt="image" src="https://github.com/user-attachments/assets/6fd4d064-a7f4-425a-8bbb-fc80c77f94e4" />
> 2-2. 2024년 12월 조회 결과
> <img width="796" alt="image" src="https://github.com/user-attachments/assets/49121b30-aee2-4b45-9a34-7869983db6cb" />
>
> 2-3. 2025년 1월 조회 결과
> <img width="794" alt="image" …

[#65] Feat: 일기 모아보기 API 구현

---

.gitignore
build.gradle
src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/converter/AuthenticationCodeConverter.java
src/main/java/umc/GrowIT/Server/domain/AuthenticationCode.java
src/main/java/umc/GrowIT/Server/domain/enums/AuthType.java
src/main/java/umc/GrowIT/Server/domain/enums/CodeStatus.java
src/main/java/umc/GrowIT/Server/repository/AuthenticationCodeRepository.java
src/main/java/umc/GrowIT/Server/service/authService/AuthService.java
src/main/java/umc/GrowIT/Server/service/authService/AuthServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java
src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/AuthDTO/AuthResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java
src/main/resources/templates/email-authentication.html

> 인증 메일 전송 API 개발
> - application.yml 파일 변경 (노션에 업데이트하겠습니다)
> - build.gradle 의존성 추가 (이메일 전송, 랜덤 인증번호 생성 관련)
> - 인증번호 전송용 템플릿 추가로 인해 yml만 제외하도록 .gitignore 변경
> - 인증번호 저장을 위한 entity 추가
> - 이메일 전송 관련 controller, service, repository, 에러 등 작성
> - 회원탈퇴, 인증메일전송, 인증번호확인 user -> auth로 도메인 변경
> 1. 인증 이메일 전송은 회원가입과 비밀번호 변경 2가지 경우가 존재합니다.
> 회원가입은 입력 이메일이 기존에 존재하지 않아야 하며, 비밀번호 변경은 입력 이메일이 기존에 존재해야 합니다.
> 따라서 각 경우를 type이라는 파라미터로 받아서 구분하였습니다. 또한, 인증번호를 서버에서 저장하고 관리하여야 하는데 redis 등의 선택지가 있었지만, 우선 기존 DB에 별도의 테이블을 생성하는 방식으로 정하였습니다.
> ![image](https://github.com/user-attachments/assets/b60ef485-aeca-4f00-b270-4046d059ada2)
> 2. 실행결과
> (a) 일반적인 경우
> ![image](https://github.com/user-attachments/assets/4276fabb-a7d3-4890-9a58-62fc2304bbeb)
> response는 마땅히 필요한 것이 없다고 생각되지만, 확인하기 좋도록 DB에 저장된 수신 이메일, 인증번호, 만료기간 등을 …

[#66] Feat: 인증 메일 전송 API 개발

---

src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java

> 특정 사용자의 특정 일기를 조회하는 API를 구현하였습니다.
> 1. userId는 임시로 2를 사용하였습니다.
> 1-1. 정상적인 경우
> <img width="799" alt="image" src="https://github.com/user-attachments/assets/f4cac96e-2194-4efa-ab95-78121f03512f" />
> 1-2. 다른 사용자가 작성한 일기의 ID를 입력한 경우
> 현재 사용자의 ID는 2이지만 ID가 4인 일기를 작성한 사용자의 ID는 3입니다.
> <img width="684" alt="image" src="https://github.com/user-attachments/assets/4be1ac3a-c6e4-4ad6-8def-41e94a22e65d" />
> <img width="802" alt="image" src="https://github.com/user-attachments/assets/7da466b8-6020-42e5-88f8-1c82736ed723" />
> 1-2-1. userId를 3으로 변경하고 똑같이 실행시켜보았습니다.
> <img width="800" alt="image" src="https://github.com/user-attachments/assets/ca784d90-db3f-4c72-b1dd-b2e1803c4bcc" />
> 1-3. 존재하지 않는 일기의 ID를 입력한 경우
> <img width="797" alt="image" …

[#65] Feat: 특정 일기 조회 API 구현

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/domain/Diary.java
src/main/java/umc/GrowIT/Server/domain/common/BaseEntity.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java

> 특정 사용자의 특정 일기를 수정하는 API를 구현하였습니다.
> + 기존 하드코딩된 userId를 accessToken을 통해 받아오도록 수정하였습니다.
> accessToken의 유효시간이 짧아서 테스트하실 때 시간이 지나면 오류가 발생합니다 참고해주세요.
> 1. 이메일 로그인 API를 통해 로그인한 후 발급된 accessToken을 Authorize에 입력합니다.
> 1-1. 해당 user가 작성한 일기가 있어야 이후 과정을 테스트할 수 있습니다.
> 아래의 쿼리문을 변경하여 로그인할 user의 일기 데이터를 넣어주세요.
> ```
> insert into diary(id, user_id, content, created_at, updated_at)
>   values(6,32, '첫번째 일기 수정전', NOW(), NOW()),
>          (7,32, '두번째 일기 수정전', NOW(), NOW());
> ```
> <img width="957" alt="image" src="https://github.com/user-attachments/assets/e86f2271-f5b3-4200-9b6e-1f31eec1133d" />
> 2. 일기 수정 API에 토큰 내용과 DiaryId를 입력 후 수정 내용을 입력합니다.
> <img width="959" alt="image" src="https://github.com/user-attachments/assets/e64586fb-7978-4d92-b2f1-b5875c81f922" />
> 2-1. 수정된 것 확인
> <img width="701" …

[#84] Feat: 일기 수정하기 API 구현

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/domain/Diary.java
src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

> 일기 엔티티에 작성하는 날짜를 기록할 필드를 추가하고
> 그에 맞게 API들을 수정하였습니다.
> (date값이 기존에는 created_at의 정보가 들어가는 것에서 사용자가 일기를 작성할 때 특정 날짜를 지정하고 작성하기 때문에 그 특정 날짜를 저장하는 date 값이 들어가도록 변경)
> 1. 로그인 후 API 테스트
> 2. 로그인한 유저의 ID로 일기를 생성한 후 진행해야합니다.
> 3. Swagger 테스트
>
> 3-1. 특정 일기 조회 API에서 date 확인
>3-2. 일기 작성 날짜 조회 API에서 date 확인
> 3-3. 일기 모아보기 API에서 date 확인

[#90] Refactor: 일기를 작성하는 날짜 필드 추가

---

.github/workflows/dev_deploy.yml

> .github.workflows/dev_deploy.yml파일 추가
1. Trigger
- develop 브랜치에 push 발생
- GitHub Actions 워크플로우 시작
2. Build Job
- 저장소 코드 체크아웃
- JDK 17 설정
- application.yml 파일 생성 (GitHub Secrets에서 설정값 가져옴)
- gradlew 실행 권한 부여
- Gradle로 프로젝트 빌드
- 빌드된 JAR 파일을 아티팩트로 업로드
3. Deploy Job
- build job 완료 후 시작
- 빌드된 JAR 파일 다운로드
- EC2 배포 과정
- private_key.pem 생성
- JAR 파일을 EC2로 전송(scp)
- SSH로 EC2 접속
- 기존 Java 프로세스 종료
- 새 버전 애플리케이션 실행
- 민감정보(private key) 삭제
> github action 실행여부 확인예정

[#92] Setting : CI/CD파일 추가

---

.github/workflows/dev_deploy.yml

> 빌드실패 오류 수정
build.gradle파일에 빌드전 테스트를 수행하는 부분이 있는데 ci/cd과정에서는 생략하도록 수정했습니다.
```
- name: Build with Gradle
uses: gradle/gradle-build-action@v2
with:
arguments: build -x test  # 테스트 제외하고 빌드
```
> 
- 노랑 : 진행중
- 초록 : 성공
- 빨강 : 실패

[#100] Setting : 빌드실패 오류 수정

---

src/main/java/umc/GrowIT/Server/converter/TokenConverter.java
src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java

1. 기존 코드
- 회원가입, 로그인 API는 응답으로 AT,RT 데이터를 주기때문에 accessToken, refreshToken 을 한번에 발급하는 generateToken() 메소드가 있었습니다.
- 토큰 재발급은 accessToken 만 발급해서 generateAccessToken() 메소드를 만들었는데, 기존 generateToken() 메소드와 코드가 중복되는 문제 발생했습니다.
2. 리팩토링
- accessToken, refreshToken 을 각각 발급하는 generateAccessToken(), generateRefreshToken() 메소드와 accessToken과 refreshToken 을 함께 발급하는 generateToken() 메소드를 만들어 코드 중복을 막고 기능을 분리했습니다.
스웨거를 통해 회원가입, 로그인, 토큰 재발급 시 토큰이 정상적으로 발급되는 것을 확인했습니다.
- 회원가입
- 로그인
- 토큰 재발급

[#108] Refactor: JWT 토큰 발급 코드 리팩토링

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/converter/GroConverter.java
src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
src/main/java/umc/GrowIT/Server/domain/Item.java
src/main/java/umc/GrowIT/Server/repository/GroRepository/GroRepository.java
src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
src/main/java/umc/GrowIT/Server/service/GroService/GroCommandService.java
src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/GroController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/GroSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroResponseDTO.java

> 홈화면과 아이템샵에서 사용할 그로 이미지와 착용한 아이템들 이미지들을 조회하는 API입니다.
> 
> 진행 단계는 다음과 같습니다.
> 스프링부트에서 사용자의 그로 레벨을 판단 + 착용시켜 놓은 아이템들을 조회
> -> S3 key값을(그로의 경우에 하드코딩 / 아이템의 경우 DB 조회) 통해 해당 이미지들에 접근할 수 있는 Pre-Signed URL을 발급
> -> 프론트엔드에 반환
> 
> 여기에서 객체 URL이 아닌 Pre-Signed URL을 사용하였습니다.
> Pre-Signed URL은 만료기간이 존재하는 S3 임시 접근 URL이라고 이해하면 될 것 같습니다.
> 이미지 업로드의 경우에 가장 효율적이지만, 이미지 불러오기의 경우에도 보안 측면에서 좋을 것이라 판단하여 사용하였습니다.
> 
> 홈화면으로 이동 or 아이템샵으로 이동할 때마다 URL을 새로 발급받아 해당 URL로 접근한다면 만료된 URL에 대해서 재접근하여 이미지를 못 얻는 일은 없을 것이라 생각합니다. 일단, 유효기간을 1일로 설정해 두었지만 이후 분 단위로 짧게 변경할 것 같습니다.
> 
> 개념에 대해서는 아래 자료에서 간단하게 확인해주세요
> https://inpa.tistory.com/entry/AWS-%F0%9F%93%9A-S3-Pre-signed-URL-%EA%B3%B5%EC%9C%A0%ED%95%98%EA%B8%B0
> 1. JWT 토큰 연동한 상태에서 해당 API를 실행하면 아래와 같은 결과를 얻을 수 있습니다.
> …

[#105] Feat: 그로와 착용 아이템 이미지 조회 API 개발

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/domain/Diary.java
src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java

> ### 확인해주셔야할 내용들 입니다!
> 일기 생성 시 -> 날짜 검사, 글자 수 검사 기능 추가
> 날짜검사: 오늘 이후의 날짜 x, 해당 날짜에 이미 일기가 존재하는 지 확인
> 일기 수정 시  -> 글자 수 검사 기능 추가
> - 해당 기능을 추가함으로 오늘 이전의 날짜에만 일기를 작성(100자 이상)할 수 있고 같은 날에 두 개 이상의 일기가 작성불가합니다. 
> 1. 현재 EC2 문제로 로컬 DB에서 테스트 하였습니다.
> 1-1. Diary 테이블의 content가 VARCHAR에서 TEXT형으로 변경되어야 합니다.
> 2. 로그인 후 테스트 진행
> 3. 생성 시
> 3-1. 100자 이내로 작성 후 생성 요청 시
> 3-2. 오늘 이후의 날짜와 함께 생성 요청 시(PR작성일: 2025-01-27)
> 3-3. 이미 해당 날짜에 일기가 존재할 때 생성 요청 시
> 4. 수정 시
> 4-1. 100자 이내로 수정 후 수정 요청 시

[#101] Feat: 일기 생성(수정 시) 날짜,글자 수 검사 기능 추가

---

src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
src/main/java/umc/GrowIT/Server/domain/Item.java
src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryService.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ItemController.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/dto/GroDTO/GroRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java

- 상점에서 아이템마다의 배경색 설정을 위해 ItemDTO에 backgroundColor를 추가
- item 도메인에 background필드를 추가
- responseBody의 "imageUrl"에 image_key가 전달되는 문제 해결
- userController 하드코딩부분 userId를 사용하도록 수정
- ItemConverter에서 status(착용여부) 누락오류 수정
- 그로 생성 api 명세서 예시값 추가
- 카테고리별 아이템 조회
- 보유중인 아이템만 조회

[#122] Feat : 상점 아이템 조회/보유중인 아이템 조회 api 관련코드 수정 및 요구사항 반영

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

> 일기 모아보기 API의 성공 예시에 다음 사진과 같이 diaryId가 보이지 않는 문제가 있었습니다.
>
> 이유는 DiaryRequestDTO와 DiaryResponseDTO에 동일한 이름의 DiaryDTO가 있었기 때문인 것 같습니다.
> 따라서 DiaryDTO의 이름을 변경함과 동시에 다른 DTO의 이름도 좀 더 명확하게 변경하였습니다.
> 1. 기존 200 code에 대한 응답
>
> 2. 변경 후 200 code에 대한 응답
><img width="705" alt="image" src="https://github.com/user-attachments/assets/9052d792-4aa6-4885-bbdb-f7d084485663" />
>

[#118] Refactor: 일기 관련 API 명세서 수정

---

src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java

> S3에서 폴더명/파일명이 변경됨에 따라, 하드코딩되어 있던 그로 이미지 키값을 수정하였습니다.
> 프론트엔드 연동을 고려하여 하드코딩 방식 자체는 유지한 채로 오류만 급히 수정하였습니다.
> 초기 ERD 설계 형태를 따르다보니 하드코딩 방식을 사용하였습니다만 추후에 그로 이미지의 경로도 DB에서 관리하는 방향으로 리팩토링하는 것이 낫지 않을까 합니다. 
> 1. 로직 자체는 수정하지 않아서 실행에 이상 없습니다.
> 2. 참고로 관련 API는 '그로와 착용 아이템 이미지 조회 API'입니다.

[#127] Refactor: 그로 이미지 key값 수정

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java

> 1. 일기 수정 시 100자 제한이 없다고하여 해당 내용 반영
> 2. 기존 내용과 동일한 내용으로 수정 요청 시 에러코드 추가
> 1. 유저의 현재 일기 목록
> 2. id가 8인 일기 변경 시
> 3. 동일한 내용으로 수정 시(2번 내용과 동일하게 한번 더 요청하면 됩니다.)

[#130] Feat: 일기 수정 API 변경

---

src/main/java/umc/GrowIT/Server/apiPayload/code/ErrorReasonDTO.java
src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/config/SecurityConfig.java
src/main/java/umc/GrowIT/Server/jwt/CustomAuthenticationEntryPoint.java
src/main/java/umc/GrowIT/Server/jwt/CustomUserDetails.java
src/main/java/umc/GrowIT/Server/jwt/CustomUserDetailsService.java
src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationException.java
src/main/java/umc/GrowIT/Server/jwt/JwtAuthenticationFilter.java
src/main/java/umc/GrowIT/Server/jwt/JwtTokenUtil.java
src/main/java/umc/GrowIT/Server/service/authService/AuthServiceImpl.java
src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoService.java
src/main/java/umc/GrowIT/Server/service/kakaoService/KakaoServiceImpl.java
src/main/java/umc/GrowIT/Server/service/refreshTokenService/RefreshTokenCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/userService/UserCommandService.java
src/main/java/umc/GrowIT/Server/service/userService/UserCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/userService/UserQueryService.java
src/main/java/umc/GrowIT/Server/service/userService/UserQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/AuthController.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java

1. 회원탈퇴를 했는데도 accessToken 으로 인증 필터를 거치는 API 에 대해 요청 가능한 경우 (유효기간 남아서)
2. 회원탈퇴를 했는데도 인증 필터를 거치지 않는 API 에 대해 요청 가능한 경우
위와 같은 경우가 생겨서 코드를 업데이트 했습니다.
1번 해결 방법
- accessToken 에서 userId 값을 읽어온 후, userId 값으로 DB에서 user를 조회
- 유저의 상태값(ACTIVE, INACTIVE) 를 확인 후 INACTIVE 인 경우 예외처리를 했습니다.
2번 해결 방법 (accessToken 이 필요하지 않은 로그인, 인증번호 보내기(비밀번호 찾기를 위한), 토큰 재발급 API)
- 각각의 API 에서 유저의 상태값(ACTIVE, INACTIVE) 를 확인 후 INACTIVE 인 경우 예외처리를 했습니다.
-> 이 경우 서비스 단에서 "유저 상태값 확인 및 예외처리하는 코드"가 중복돼서 추후에 리팩토링 고려하겠습니다.
+) 추가 / 여담
- 기존 코드에서 토큰에 userStatus 값 넣어서 비교하려고 했는데 이 부분은 회원탈퇴 후 기존 accessToken 에는 userStatus 값이 ACTIVE 로 저장되어 있기 때문에 응답이 적절하지 않게 나와서 토큰에 userStatus 값 넣지 않고 DB 에 직접 접근해서 비교하는 방식으로 바꿨습니다.
- DB 에 직접 접근해서 비교하는 방식은 구현이 간단하지만 JWT 토큰의 Stateless 방식에 맞지 않는 다는 단점이 존재합니다. 따라서 추후에 Redis 를 사용해 블랙리스트에 accessToken 을 저장해서 …

[#124] Bug: 탈퇴 회원 처리 (토큰 인증 필터 및 API 수정)

---

src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java

> 
1. dtype x, completed true -> 완료한 챌린지 조회
2. dtype x, completed false -> 전체(미완료한) 챌린지 조회
3. dtype RANDOM, completed false -> 미완료한 랜덤챌린지 조회
4. dtype DAILY, completed false -> 미완료한 데일리챌린지 조회
기존의 코드로는 dtype에 RANDOM 또는 DAILY 값을 넣고 completed에 true값을 주면 완료한 랜덤챌린지, 완료한 데일리챌린지가 각각 조회되는 상황이었습니다. 그러나 카테고리상 완료 부분에서는 "완료한 전체 챌린지"만 있지, "완료한 랜덤챌린지" 또는 "완료한 데일리챌린지"는 존재하지 않다고 생각하였습니다. 그래서 하나로 통합하였던 메서드를 **1. 완료/미완료 챌린지 조회(dtype 무시) 2. dtype에 대해 미완료챌린지 조회** 이렇게 나누는 식으로 수정하게 되었습니다. 코드에 주석 달아놨으니 이해 안되시면 말씀해주시고 수정해야 할 부분 또한 말씀해주세요! 
> 1. dtype x, completed true -> 완료한 챌린지 조회
2. dtype x, completed false -> 전체(미완료한) 챌린지 조회
3. dtype RANDOM, completed false -> 미완료한 랜덤챌린지 조회
4. dtype DAILY, completed false -> 미완료한 데일리챌린지 조회(유저챌린지에 미완료한 데일리챌린지 데이터가 없어 빈 리스트가 반환되는 것입니다 -> 데이터가 존재한다면 미완료한 랜덤챌린지를 조회할때처럼 챌린지 목록이 …

[#144] Refactor: 챌린지 현황 조회 메서드 및 쿼리문 수정

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/ImageHandler.java
src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/service/ImageService/ImageService.java
src/main/java/umc/GrowIT/Server/utils/ImageUtils.java
src/main/java/umc/GrowIT/Server/utils/SecurityUtils.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ImageDTO/UploadImageResponse.java

> 이미지 첨부(S3 활용하여 이미지 첨부하는 기능 구현)
챌린지 인증 작성을 할때 이미지를 첨부하는 기능, 인증내역을 조회할때 이미지를 불러오는 기능, 챌린지 인증 내역을 수정할 때 이미지 수정하는 기능(이미지를 수정하지 않으면 이전 이미지가 그대로 적용) 이렇게 3가지를 aws s3를 활용하여 구현하였습니다.
s3 환경설정은 아래를 참고하시면 됩니다.
#91 
컨트롤러에서 @RequestBody 는 multipart/form-data 요청을 처리할 수 없기 때문에 @ModelAttribute 를 사용하였습니다.
인증 작성 부분에서 imageUrl은 처음에 null값이며 값이 들어오면 이를 유저챌린지에 저장하고, 인증 수정 부분에서 oldImageUrl과 newImageUrl로 나눠 사용자가 이미지를 수정하면 기존 이미지(oldImageUrl)는 s3에서 삭제되고 새로운 이미지(newImageUrl)가 업데이트되는 형식입니다.
send empty value 체크박스가 뜨지 않게 dto 스키마에 required=true를 넣어 해당 필드를 필수값으로 지정할 수 있으나
```java
@Schema(description = "인증 이미지 파일 (multipart/form-data)", required = true)
private MultipartFile certificationImage;
``` 
인증이미지만 수정하거나 소감만 수정하는 상황까지 생각하다보니 필수값으로 지정해버리면 이미지와 소감 둘 다 수정해야 하는 상황 하나로 제한되기 때문에 일단 체크박스가 존재하게 두었습니다. 그러나 저도 테스트할 때 …

[#143] Feat: 챌린지 인증 이미지 첨부(S3 활용)

---

src/main/java/umc/GrowIT/Server/converter/ItemConverter.java
src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
src/main/java/umc/GrowIT/Server/repository/UserItemRepository.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/ItemService/ItemQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/ItemDTO/ItemResponseDTO.java

- ItemResponseDTO
-  __`String groImageUrl;`__ 추가
- ItemCommandServiceImpl
- updateItemStatus 주석처리 되어있던 기존코드 제거
기존에 s3에 저장된 이미지의 실제 url을 직접 전달하는 방식에서 Pre-signed URL을 생성해서 전달하는 방식으로 변경하였습니다. 코드는 기존에 진성님께서 구현하셨던 _`GroCommandServiceImpl`_을 참고했습니다.
- ItemQueryServiceImpl
-  createItemPreSignedUrl <- 리스트용 이미지 Pre - sigened url생성
- createGroItemPreSignedUrl <- 착용용 이미지 Pre - sigened url생성
-----
- 보유중인 아이템 조회 (GET - /users/items)
- 카테고리별 아이템 조회 (GET - /items)

[#135] Refactor : 착용용 이미지 응답 추가 및 이미지url 전달방식 수정

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

> 수정 내용이 너무 길어져서 새로 올립니다.
챌린지 인증 내역 수정 관련 부분(ex. dto 수정, oldImageUrl 변수 처리)은 따로 refactor 브랜치 파서 수정하겠습니다..
🐎 선택한 챌린지 저장 api 수정사항
- 기존: challengeId를 PathVariable로 입력하고 dtype을 DAILY, RANDOM 중 선택하여 넘기는 식
- 변경: challengeId를 dtype과 함께 RequestBody 리스트 형태로 넘기는 식(dtype은 STRING값으로 입력받음, "RANDOM" 또는 "DAILY"로 입력해야 하며 다른값을 입력하면 에러 발생)
ChallengeCommandServiceImpl 파일의 selectChallenges 코드 내용이 많이 수정되었는데 데일리챌린지는 최대 2개, 랜덤챌린지는 최대 1개.. 이런식으로 예외 처리를 다 하다보니 조금 길어지고 복잡해졌습니다. ai가 챌린지를 추천해주면 사용자가 그 중 챌린지를 1개~3개 선택하여 저장할 수 있다고 해서 dtype에 따라 예외 처리를 하였습니다.
(ex. 챌린지를 2개 선택하여 저장하는 경우 데일리챌린지2개를 선택해도 되고 데일리챌린지1개+랜덤챌린지1개 이런식으로 선택해도 된다고 합니다. -> 챌린지를 선택하여 저장하는 화면에서는 dtype이 데일리인지, 랜덤인지 따로 노출을 하지 않는다고 하여 챌린지 선택하여 저장 시 dtype 처리는 ai 챌린지 추천 기능 작업하면서 수정해야할 것 같습니다..)
데일리챌린지가 0개이고 동시에 랜덤챌린지가 0개이면 totalChallengesCount를 선언하지 않고도 예외 …

[#155] Refactor: 선택한 챌린지 저장 API 수정

---

src/main/java/umc/GrowIT/Server/domain/Item.java
src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java

> 아이템 이미지를 '상점 썸네일/착용'에 따라 구분하기 위해 필드가 별도로 존재하게 되었습니다.
> 이에 따라서, 기존에 구현한 그로&착용 아이템 이미지 조회 API에서 착용 시를 위한 필드인 groImageKey를 사용하도록 변경하였습니다
> 추가적으로 진우님이 구현하신 상점 관련된 아이템 조회 API에서도 Pre-Signed URL 사용하는 방식으로 변경하셨다고 전해들어서, imageUrl과 groImageUrl 필드는 필요없다고 판단되어 삭제하였습니다.
> 사용하는 필드만 변경된 것이기 때문에 특이사항 없습니다

[#160] Refactor: 그로&착용 아이템 이미지 조회 API 수정

---

src/main/java/umc/GrowIT/Server/repository/ItemRepository/ItemRepository.java
src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java

> 
- src/main/java/umc/GrowIT/Server/service/GroService/GroCommandServiceImpl.java
```
//기본 핑크색 PLANT 조회
Item basicPlantItem = itemRepository.findByName("핑크 머그컵")
.orElseThrow(() -> new ItemHandler(ErrorStatus.ITEM_NOT_FOUND));
```
이 부분은 후에 DB가 초기화 된 후 Item테이블의 id가 변경될  수 있기때문에 아이템 이름으로 검색하도록 하드코딩으로 구현했습니다.
- 토큰 입력후 테스트 진행(userId 42)
- gro테이블 레코드 생성
- userItem 테이블에 레코드 2개 생성

[#162] Feat : Gro 생성시에 핑크색 PLANT 설정 추가

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/KeywordHandler.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/OpenAIHandler.java
src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/converter/KeywordConverter.java
src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
src/main/java/umc/GrowIT/Server/repository/ChallengeKeywordRepository.java
src/main/java/umc/GrowIT/Server/repository/ChallengeRepository.java
src/main/java/umc/GrowIT/Server/repository/KeywordRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/KeywordDTO/KeywordResponseDTO.java

> ❗ 먼저, 노션에서 yml파일 수정 필요합니다 ❗
> [OpenAI API 호출 -> 감정 -> 챌린지] 를 모두 구현한 API라서 작업 내용이 많습니다...!
> 최대한 신경썼지만 OpenAI API, DB 데이터, 중복 방지, 랜덤 등을 동시에 고려하다보니, 예외 체크가 더 필요한 부분이 없을 지를 중점적으로 확인해주시면 감사하겠습니다.  ex) GPT 호출 결과가 감정 '3개'가 맞는지
> (제가 테트스하는 동안에는 별다른 이상이 없었고, 되도록 빠르게 PR 올리고 피드백 통해서 리팩토링하는게 낫다고 생각되어 올립니다.)
> 
> 주요 흐름 간단하게 설명드리겠습니다.
> 1) 사용자로부터 `일기 내용` 전달 받음
> 2) OpenAI API를 호출하여 `일기 내용`과 가장 적합한 3개의 `DB 감정`들을 매칭
> 3) 매칭된 `감정` 3개 중 2개를 랜덤 선택
> 4) 2개의 `감정`과 연관관계를 맺고 있는 `챌린지`들 중에서 중복되지 않도록 랜덤하게 각 1개씩 선택 (=데일리 챌린지)
> 5) 데일리 챌린지로 선택되지 않은 `챌린지` 중에서 랜덤하게 1개 선택 (=랜덤 챌린지)
> 6) 감정들과 데일리/랜덤 챌린지 반환
> DB가 아직 정리되어 있지 않기 때문에, 현재 PR에서는 ID 1~5의 감정만 사용하며 각 감정에는 제가 임의로 챌린지를 매칭하여 놓았습니다. 이후에 DB 전체 감정들을 사용하도록 리팩토링하겠습니다.
> 1. 일기 내용을 전달 (로그인하여 JWT 토큰 세팅이 완료된 상태여야 합니다.)
> …

[#164] Feat: 챌린지 추천 API 구현

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/domain/DiaryKeyword.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

> 서비스 흐름 [일기 저장 -> 일기 분석 -> 감정 -> 챌린지] 중에서 `일기 분석 ~ 챌린지`를 구현한 API입니다.
> 일기 저장 API와 합치는 식으로 진행하려 했으나, #173 해당 이슈를 읽어보시면 별도의 API를 유지하기로 정리되었습니다.
> 그리고 Request로 일기 ID를 전달받기 때문에, 챌린지 추천 API보다는 도메인 자체가 일기에 해당한다고 판단되어 `일기 분석 API`로 구분하며 이에 알맞게 코드 수정하였습니다.
> 주석을 최대한 달아두었기 때문에 이해에 어려움은 없으리라 생각됩니다! 옮기면서 보완된 내용이 있어, 코드도 확인 부탁드립니다.
> 1. 작성된 일기 ID를 전달받으면 해당 일기의 내용에 대해 분석하여 감정과 연관된 챌린지를 반환합니다.
> <img width="532" alt="image" src="https://github.com/user-attachments/assets/efebcc66-0cf6-483f-bc50-36dae872d125" />

[#173] Refactor: 챌린지 추천 API 수정 (->일기 분석 API)

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java

- 카카오 로그인, 소셜 회원가입 관련 API 명세 업데이트
- 회원 탈퇴 관련 예외 상태 코드 추가
> 1. <테스트 방법을 상세히 적어주세요 (스크린샷 첨부 가능)>

[#177] Docs: 회원 관련 스웨거 API 명세 업데이트

---

src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java

> 1. 직접 일기 작성 시에 크레딧 개수 증가
> 2. 음성 일기 작성 시에 크레딧 개수 증가 
> -  User 엔티티에 updateCurrentCredit 메소드만 존재하여 updateTotalCredit 메소드도 추가하였습니다.
> -  일기 생성하는 두 가지 서비스 코드에 크레딧 개수 증가하는 부분을 추가하였습니다.
> 1. 현재 크레딧과 누적 크레딧 수 확인 
> 현재 둘 다 6
> 2. 직접 일기 작성 시 크레딧 증가 확인
> 아무내용으로 100자 이상 일기를 작성합니다.
> - 일기가 저장된 것 확인 
> 3. 변경된 현재 크레딧과 누적 크레딧 수 확인
> 둘 다 8로 증가된 것을 확인할 수 있습니다.
> 4. 음성 일기 작성 시 크레딧 증가 확인
> AI와 대화를 마구마구 한 후에 일기 생성 API 호출
> - 일기가 저장된 것 확인
> 5. 변경된 크레딧 수 확인
> 둘 다 10으로 증가된 것을 확인할 수 있습니다.

[#181] Feat: 일기 작성 시 유저 크레딧 개수 증가

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

> -converter에서 certificationDate를 createdAt로 불러오고 있어서 그 부분 수정하였습니다.
- UserChallenge에 certificationDate 필드 추가하였고,
```java
@Column(nullable = false)
private LocalDateTime certificationDate;
``` 
로 선언하면 00:00:00 00:00:00 null로 저장되어 에러가 떠서, 처음에는 createdAt 뜨게하고  챌린지 인증 작성을 하면 인증한 날짜와 시간이 나오게 수정하였습니다.
- 프론트에서 decodingError가 난다고 하여 LocalDateTime 값을 포맷하여 전송하는 식으로 수정하였습니다.
잘못된 부분 있으면 알려주세요!
> x

[#194] Refactor: 챌린지 인증 내역 조회 certificationDate 수정

---

src/main/java/umc/GrowIT/Server/GrowItServerApplication.java
src/main/java/umc/GrowIT/Server/repository/AuthenticationCodeRepository.java
src/main/java/umc/GrowIT/Server/scheduler/Scheduler.java

> 인증 번호를 받기 위해 메일을 전송하는 경우의 데이터를 DB에서 관리 중입니다. 
> 이때, 오래 누적된 데이터들을 삭제하는 스케줄러를 구현하였습니다.
> 만료시간이 15일 지난 데이터를 매일 자정에 삭제합니다
> (테스트는 변경해서 진행하였습니다)
> 
> 현재 코드는, 인증 여부와는 별개로 만료시간만 오래되었다면 삭제하도록 하였는데 인증 완료한 데이터는 유지할 필요가 있을까요??
> 1. 14일 기준으로 변경하였기 때문에, ID 6~9 데이터가 삭제되어야 함
> ![image](https://github.com/user-attachments/assets/0332a064-1149-421f-b317-1b34057d6e89)
>
> 2. 설정해둔 22시 18분이 되면 삭제되는 것을 확인할 수 있음
> ![image](https://github.com/user-attachments/assets/f04b22eb-d900-41b5-8486-caab0eb1fe78)

[#196] Feat: 스케줄러 - 오래된 인증번호 삭제

---

src/main/java/umc/GrowIT/Server/config/OpenAiConfig.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/OpenAIDTO/ChatGPTRequest.java

1. 모델이 일기를 잘못 분석
2. DB에 없는 감정을 포함하여 응답
1. 일기를 잘못 분석하는 일은 4o-mini 로 변경 및 temperature 값 조절로 크게 개선됐습니다.
여기서 추가로 파인튜닝을 통해 특정 문장 패턴에 대한 학습을 시켜서 좀 더 일기의 전체 맥락에 맞는 3개의 감정을 추출하도록 했습니다.
- ex) 요즘 중요한 시험을 앞두고 준비하느라 걱정이 많이 됐다. 하지만 오늘 결국 긴장하지 않고 시험을 잘 치뤘다고 느꼈고, 준비한 만큼 결과가 잘 나올 거라고 기대한다.
- <img width="195" alt="Screenshot 2025-02-15 at 3 13 57 PM" src="https://github.com/user-attachments/assets/c4b196e1-aa3f-41dd-b045-ace56b84f332" /> : **gpt-4o-mini** 
- <img width="220" alt="Screenshot 2025-02-15 at 3 14 36 PM" src="https://github.com/user-attachments/assets/fc2697cd-b5d7-4790-8266-d8e6a20d1c62" /> : **파인튜닝v3.3(200개 데이터 학습)**
- <img width="216" alt="Screenshot 2025-02-15 at 3 14 48 PM" src="https://github.com/user-attachments/assets/f9ab8465-3135-4f88-9a30-69d51d958fb0" /> : **파인튜닝v3.4(600개 데이터 학습)** …

[#198] Bug: 일기-키워드 추출 시, 잘못된  분석 및 DB 없는 감정 응답 개선

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

> 
변수명을 수정하여, 기존에 있던 UserChallenge 데이터에서 certificationImageUrl을 조회하면 null로 뜨고
일기 작성 - 분석 - 챌린지 저장 - 인증 작성 절차를 새로 거치면 작성한 certificationImageUrl이 잘 조회됩니다. (당일에 챌린지 인증 작성을 마쳐서 테스트를 못한다면, "챌린지 인증 내역 수정" 에서 url 수정하면 문제없이 잘 조회되는거 확인할 수 있습니다.)
-> 프론트분께 수정사항 말씀드렸습니다.
-> UserChallenge 엔티티에서 certificationImageUrl로 수정하였더니 DB에 certification_imageurl 필드가 새로 추가되었습니다. (certification_image 필드는 그대로)    UserChallenge 데이터 초기화할 때 참고해주세요.
❗ 자정이 지나도 챌린지 홈 조회 부분이 초기화되지 않는다고 하셔서 ec2 터미널에서 timezone Etc/UTC -> Asia/Seoul 변경하였습니다. UTC 기준 한국시간은 9시간 차이난다고 하니 테스트하시게 되면 참고해주세요. (자정이 지났는데도 초기화되지 않으면 timezone 적용이 안된거일수도 있으니 문제 생기면 말씀해주세요!)
> x

[#200] Refactor: 챌린지 관련 코드 수정

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/apiPayload/exception/FlaskHandler.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java

> 일기 분석 API 과정에서 OpenAI가 DB에 없는 감정을 반환하는 경우, 플라스크로 전송하여 DB에 저장된 감정 중 가장 유사한 감정으로 매칭함으로써 오류를 방지하였습니다.
> 유사도 매칭 자체의 한계와 중복 방지를 위한 차선책으로 인해 완전히 만족스러운 결과가 나오지 않을 수도 있지만, DB에 없는 감정이 반환되는 경우가 드물고 오류 방지를 위한 조치이기 때문에 현재로서는 최선의 방법이라고 생각됩니다.
> 현재 테스트용 코드로 PR을 올렸는데, 이 상태로 Merge하여 Ec2 위에서 정상적으로 플라스크와 연결이 되는지 확인한 다음에 이상 없는 것이 확인되면 주석 처리해둔 코드로 다시 PR 올릴 예정입니다.
> X

[#201] Fix: 일기 분석 API - 플라스크 연결

---

src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java

> https://github.com/7-umc-GrowIT/GrowIT-SpringBoot/pull/210
> DB에 없는 감정이 반환되어야 플라스크를 호출하도록 되어있기 때문에 이전 PR에서 플라스크를 연결할 때 테스트 코드로 올렸습니다.
> 
> ![image](https://github.com/user-attachments/assets/c72ccb05-1bd9-478a-a280-9835ed7c5bf9)
> 방금 ec2의 스웨거로 테스트한 결과, 테스트 코드 정상 실행되는 것으로 확인되었습니다.
> 따라서, 테스트 코드는 주석 처리하고, 정상 코드로 변경해 두었습니다.
> 1. X

[#211] Refactor: 일기 분석 API - 플라스크 연결 수정

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/repository/ChallengeKeywordRepository.java
src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/repository/diaryRepository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeQueryServiceImpl.java

> 챌린지 홈 조회 시 recommendedChallenges 업데이트
(수정 사항)
- 일기를 삭제하면 챌린지 홈에서 recommendedChallenges 가 빈 리스트로 반환
- 삭제하기 전 일기 분석으로 저장한 챌린지들은 UserChallenge에 유지
- 챌린지 현황 조회 시 해당 챌린지들 조회 가능, 인증 작성 가능
일기를 삭제해도, 분석하여 추천받은 챌린지들 중 사용자가 n개의 챌린지를 선택하여 UserChallenge 에 저장하였다면 데이터는 유지됩니다. (즉, 일기를 삭제해도 저장한 UserChallenge 데이터는 삭제되지 않는다는 의미)
1. 오늘 날짜로 일기 작성
2. 일기 분석 후 챌린지 홈 조회하였을 때 추출된 3가지 키워드가 조회되는지 확인(recommendedChallenges 는 빈 리스트)
3. "선택된 챌린지 저장 API"에서 추천받은 챌린지 3개 중 1~3개 선택하고 저장하기
4. 챌린지 홈 조회하였을 때 recommendedChallenges 에 저장한 챌린지 목록이 조회되어야함. (만약 챌린지를 2개 저장하였다면 2개만 조회되어야함.)
5. **해당 일기를 삭제하고 챌린지 홈 조회를 하였을 때 키워드와 추천챌린지 둘 다 빈 리스트로 반환되는지 확인**

[#209] Refactor: 챌린지 홈 조회 시 recommendedChallenges 업데이트

---

src/main/resources/templates/email-authentication.html

> 기존 템플릿에서는 인증번호에 따라 인증번호를 둘러싼 흰색 박스의 크기가 달라지고, 유효시간 안내가 없는 등이 부족하였습니다. 이를 개선하기 위해 타임리프 코드를 수정했습니다. HTML/CSS 영역이라 AI 사용하였습니다. 코드 리뷰는 안해주셔도 될 것 같습니다!
> 기존 (좌-구글 / 우-네이버)
<p align="center">
</p>
> 변경 (웹)
<p align="center">
</p>
> 변경 (모바일)
<p align="center">
</p>

[#217] Refactor: 인증 메일 템플릿 보완

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/domain/UserChallenge.java
src/main/java/umc/GrowIT/Server/service/ChallengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeRequestDTO.java

> bug로 하고 챌린지 홈 조회 부분 수정하려고 하였으나 dto 먼저 수정하여 pr 올립니다.
dto 변수명 createdAt로 하려다가 date로 설정하면서 UserChallenge에 date 필드 추가하게 되었습니다.
선택한 챌린지 저장 시 date값을 함께 넘겨줘야하며 챌린지 홈 조회 시 date 기준으로 조회할 예정입니다.
일기 삭제하면 관련 유저챌린지도 삭제하는 방식으로 변경되어 -> 일기 삭제 작업 끝나면 챌린지 홈 수정 작업 들어가겠습니다!
> x

[#219] Refactor: 챌린지 date 필드 추가

---

src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java

> - 일기 삭제 API에서 해당 일기를 작성하면서 선택한 UserChallenge도 같이 삭제되도록 구현하였습니다.
> 1. 삭제할 일기의 date를 사용해서 UserChallenge 리스트를 조회합니다.
> 2. 조회된 UserChallenge 들을 삭제합니다.
> X

[#223] Feat: 일기 삭제 API에서 관련된 UserChallenger 삭제 기능 추가

---

src/main/java/umc/GrowIT/Server/converter/FlaskConverter.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/dto/FlaskDTO/FlaskRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/FlaskDTO/FlaskResponseDTO.java

> #229
> 자세한 내용은 상단의 이슈 참고 부탁드립니다!
> 
> 수정된 일기 분석 API (SpringBoot)
> 1. 일기 내용을 OpenAI에게 전달하여 감정을 분석 (DB와 무관)
> 2. OpenAI의 결과를 그대로 Flask에 전달 (DB와 비교 X)
> 3. Flask의 결과인 문자열(감정)로 DB 조회하여 이후 작업 수행
> 1. 데이터 세팅
> 감정과 챌린지 등 기본 데이터가 필요합니다.
> [노션 -> Back 개발 문서 -> DB 초기 데이터셋] 에 데모데이 때 사용한 데이터 sql문 있습니다.
> 2. 사용자 & 일기 데이터 각각 저장 필요
> 3. 로컬에서 Flask 서버까지 실행
> 4. 일기 분석 API Swagger에서 실행
> 5. 결과
> ![image](https://github.com/user-attachments/assets/2323df3d-6d2c-437a-880e-13af9ea5d7fc)
> ![image](https://github.com/user-attachments/assets/d5cd4f71-e376-4456-9b4d-9a78ab5cc499)

[#229] Refactor: 일기 분석하기 API 로직 수정

---

src/main/java/umc/GrowIT/Server/config/OpenAiConfig.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java

기존 AI 대화에서 질문이 너무 많다는 피드백이 있어 **질문보다는 공감 위주의 응답을 하도록** 조정했습니다.
시스템 프롬프트
- 질문을 하지 않도록 명시했습니다.
- 단 cnt == 3일 때만 질문 1개를 허용하는 조건 추가
사용자 프롬프트
- 매 요청마다 cnt 값을 포함하여, AI가 질문 여부를 판단할 수 있도록 수정
프롬프트만으로 제어한 방식이라, 확률 기반으로 응답을 생성하는 GPT 특성상 예외적으로 질문이 발생할 수 있습니다.
GPT가 if-else 처럼 동작하지 않기 때문입니다.
(이전 감정 키워드 추출 문제와 같은 문제가 발생합니다. 🥹 하지만 예외가 발생해도 시스템에 큰 영향을 주지 않는다는 차이점이 있습니다.)
> 1. <테스트 방법을 상세히 적어주세요 (스크린샷 첨부 가능)>

[#237] Refactor : 일기 AI 대화 개선

---

.github/workflows/dev_deploy.yml
.gitmodules
build.gradle
docker-compose.yml

개발&배포 환경의 DB 세팅이 다르며, 변경사항이 있을때마다 Notion을 변경하고 서로에게 알려주어야 하기 때문에
이를 개선하기 위해 서브모듈 도입했습니다. 서브모듈에서는 `dev(로컬 개발)` & `prod(배포)`용 yml을 각각 관리합니다.
이를 유의하시고, 특정 환경에만 필요한 설정인지/공통으로 필요한 설정인지를 구분하여 각각의 yml에 작성해주시면 됩니다.
<br>
서브모듈을 도입하였는데, 각자의 로컬 `MySQL` 세팅이 다르다보니 서브모듈을 도입했음에도 이를 매번 수정하여야 하는 번거로움이 존재합니다. 이를 위해 `Docker`를 도입하였습니다.
`Docker`는 높은 이식성이 특징이기 때문에 매번 수동으로 다운하고 설정해야하는 번거로움을 덜어줍니다.
처음 사용하신다면 간단하게 로컬에 `컨테이너`라는 별도의 환경을 구축하고 그곳에 `MySQL`을 실행시켜서 사용한다 라고 이해하시면 될 거 같습니다. 설치...는 어렵지는 않은데, 되도록 빠르게 Notion 페이지에 블로그 첨부하겠습니다. 😅
<br>
기존에는 Github Secrets의 yml을 끌어다가 CI/CD의 빌드 과정에서 사용하는 구조였고,
서브모듈을 도입하게 되며 서브모듈의 yml을 사용하도록 CI/CD를 수정하였습니다.
<br>
서브모듈과 Docker와 관련한 자세한 내용은 Notion 확인 부탁드립니다!
변경한 CI/CD 성공하는 거까지 확인하였습니다.
https://github.com/7-umc-GrowIT/GrowIT-SpringBoot/actions/runs/16994665124

[#249] Feat: 서브모듈 & Docker 도입

---

src/main/java/umc/GrowIT/Server/converter/UserConverter.java
src/main/java/umc/GrowIT/Server/domain/Gro.java
src/main/java/umc/GrowIT/Server/domain/User.java
src/main/java/umc/GrowIT/Server/service/userService/UserQueryService.java
src/main/java/umc/GrowIT/Server/service/userService/UserQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/UserController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/GroSpecification.java
src/main/java/umc/GrowIT/Server/web/controller/specification/UserSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/UserDTO/UserResponseDTO.java

마이페이지 조회 api 구현하였습니다.
해당 화면에서는 사용자의 그로의 닉네임과 구독여부를 조회하고, 구독여부에 따라 "구독 중" 라벨이 처리됩니다.
그러나 1차 출시에서 결제/구독 기능은 포함하지 않는다고 하여 User 엔티티에 isSubscribed 필드만 추가하고 주석 처리 해놨습니다.
-> 결제/구독 기능 구현되면 해당 필드까지 조회하여 반환할 예정입니다
그리고 엔티티에서는 사용자와 그로가 일대다 매핑으로 되어있는데 그로 생성 로직에서 그로 중복 처리를 진행하고 있는것으로 보아 일대일 매핑 같아서 수정하였습니다 관련 부분은 한번 확인해주세요!
```java
// Gro.java
@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "user_id", nullable = false)
private User user;
``` 
- 스웨거에서 마이페이지 조회 시 userId, 그로의 닉네임 반환
- 인증을 하지 않은 경우

[Feat/#261] 마이페이지 조회 api 구현

---

src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java
src/main/java/umc/GrowIT/Server/web/dto/KeywordDTO/KeywordResponseDTO.java

1. 기존 코드에서 선언은 되지만 사용되지 않는 자잘한 코드들 삭제하였습니다.
ex1) `User user = userRepository.findById`~ 에서 user 변수가 해당 메소드 내에서 사용되지 않는 부분
ex2) 인터페이스 파일에서 `public` 코드는 불필요하다고 생각하여 해당 부분 삭제
2. 일기 글자 수 제한은 서비스에서 조건문으로 처리하는 대신 @Valid로 처리하였습니다. (Size와 message 옵션 사용)
3. 중복 코드는 메소드 분리하여 관리하였습니다.
(1) `createDiary` 와 `createDiaryByVoice` 에서 일기 날짜 유효성 검사를 동일하게 진행하고 있어 duplicate 발생
-> `checkDiaryDate `메소드로 따로 분리하여 일기 날짜 유효성 검사를 진행하는 식으로 수정하였습니다.
```java
private void checkDiaryDate(Long userId, LocalDate date) {
// 오늘 이후의 날짜를 선택한 경우
if (date.isAfter(LocalDate.now())) {
throw new DiaryHandler(ErrorStatus.DATE_IS_AFTER);
}
// 이미 해당 날짜에 작성된 일기가 존재하는 경우
if (diaryRepository.existsByUserIdAndDate(userId, date)) {
throw new DiaryHandler(ErrorStatus.DIARY_ALREADY_EXISTS);
}
}
``` 
(2) `chatByVoice`와 `createDiaryByVoice`에서 …

[#274] Refactor: 일기 api 스키마 적용 및 서비스 로직 개선

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

1차 출시 전까지는 슬라이스 기법 -> 페이징 기법으로 다시 변경하고 카테고리별 챌린지 개수까지 조회하도록 변경되었습니다.
출시 이후에 그로 아이템 조회 시 무한스크롤 방식이 적용되면 챌린지 현황 조회에서도 동일하게 적용될 것 같습니다.
그리고 예전에 작업한 코드를 다시 보니 `totalElements` 에서 **카테고리별 챌린지 개수**를 조회하고 있더라고요.. ㅎㅎ
response body 예시는 아래와 같은데 기존과 동일하게 currentPage는 현재 페이지, totalPages는 총 페이지, totalElements는 총 요소 개수(챌린지 개수), first는 첫번째 페이지인지, last는 마지막 페이지인지. 를 의미합니다.
```java
{
"isSuccess": true,
"code": "string",
"message": "string",
"result": {
"content": [
{
"id": 1,
"title": "좋아하는 책 독서하기",
"challengeType": "DAILY",
"time": 1,
"completed": false
}
],
"currentPage": 1,
"totalPages": 1,
"totalElements": 1,
"first": true,
"last": true
}
}
``` 
**한 페이지에 5개의 챌린지가 조회됩니다!**
- 전체(미완료) 챌린지 조회
- 완료 챌린지 조회
- 미완료한 DAILY 챌린지 조회
- 완료한 DAILY 챌린지 조회
- 미완료한 RANDOM 챌린지 조회
- 완료한 RANDOM 챌린지 조회

[#276] Refactor: 챌린지 현황 조회 시 페이징 기법 적용

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/repository/UserChallengeRepository.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java

1. 하루에 인증을 할 수 있는 챌린지 개수를 10개로 제한합니다.
2. 챌린지는 제한 없이 추가 저장 가능하되, 하루에 3개 인증까지 크레딧 지급하고 4개 인증부터는 크레딧을 지급하지 않습니다.
ex: 8월 31일 기준
8월 30일 날짜의 일기 작성과 재작성으로 챌린지를 6개 저장 후 모두 인증
-> 8월 31일 날짜의 일기 작성과 재작성으로 챌린지를 5개 저장 후 인증
-> 하루에 최대 10개까지 인증 가능하므로 나머지 1개는 인증 불가
=> 다음날(9월 1일)이 되면 해당 챌린지에 대하여 인증 가능
하루에 인증 완료한 챌린지 개수를 조회할 때 `uc.createdAt = :today` 로 비교가 불가능하여, 아래처럼 startOfDay와 endOfDay 선언하여
startOfDay와 endOfDay 범위 내에서 개수를 조회하고 11번째 인증을 시도하는 경우 `하루에 10번만 인증이 가능합니다.` 에러메시지가 뜨도록 처리하였습니다.
```java
LocalDate today = LocalDate.now();
LocalDateTime startOfDay = today.atStartOfDay();
LocalDateTime endOfDay = today.atTime(LocalTime.MAX);
``` 
1. 하루에 인증을 할 수 있는 챌린지 개수를 10개로 제한합니다. `completedCount` 변수에 **오늘 날짜로 인증 완료한 챌린지 개수**를 담아, 챌린지 인증을 시도하려고 하는데 이미 인증 작성한 챌린지 개수가 10개인 경우 "하루에 10번만 인증이 가능합니다." 에러메시지를 반환합니다. …

[#288] Refactor: 챌린지 인증 작성 제한

---

src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java

일기 도메인에서는 트랜잭션 어노테이션도 사용하지 않고 기존에 존재하던 `userRepository.save(user)` 코드가 사라져서 (나 아님..)
일기 작성 시에도 사용자의 크레딧이 올라가지 않는 문제가 있었습니다.
(이전 PR에서 작업량이 많다보니 사용자 크레딧이 증가되는거까지는 확인하지 않았었던... 🥲)
X
1. 처음 사용자 크레딧
2. 일기 작성
3. 증가된 사용자 크레딧
4. 아이템 구매
5. 감소된 사용자 크레딧

[#313] Fix: 일기 작성 시  크레딧 미적립 문제 해결

---

src/main/java/umc/GrowIT/Server/apiPayload/code/status/ErrorStatus.java
src/main/java/umc/GrowIT/Server/domain/Term.java
src/main/java/umc/GrowIT/Server/domain/enums/TermStatus.java
src/main/java/umc/GrowIT/Server/repository/TermRepository.java
src/main/java/umc/GrowIT/Server/service/termService/TermCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/service/termService/TermQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/specification/AuthSpecification.java

약관 내용이 변경되거나, 추가될 때 현재 테이블로는
변경되기 전/변경된 후 사용자가 어떤 약관에 동의했는지 추적하기 어려운 문제가 있었습니다.
1. 테이블 수정
- 따라서 약관 효력 발생일(effectiveDate), 종료일 컬럼(expirationDate)을 추가해 구체적인 약관 시행 기간을 확인할 수 있게 하고
- 약관 적용 상태(status) 및 버전(version)은 쿼리 조회할 때나 어떤 약관인지 식별할 때 편리함이 있어 추가했습니다.
2. 약관 조회 및 검증 로직 수정
- 약관 조회 시 현행 약관(status=ACTIVE)만 조회
- 약관 검증 시 현행 약관(status=ACTIVE) 인지 확인
애플 로그인 PR, 현재 PR로 인해 테이블 변경돼서 서브모듈에 해당 SQL 올려놓았습니다.
추후에 PR 승인 시 로컬 DB에만 반영해주시면 서버에 따로 적용하겠습니다.
1.

[#280] Feat : 약관 목록 조회 및 검증 로직 변경

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandService.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/ChallengeController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/ChallengeSpecification.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

챌린지 삭제 api 응답이 null로 반환되도록 수정하였습니다!
미완료한 유저챌린지 삭제

[#318] Refactor: 챌린지 삭제 api 응답 반환 수정

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeQueryServiceImpl.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

원래는 일기 삭제 시, 분석된 감정키워드 + 선택했던 챌린지까지 다 삭제하는 로직이였지만 (원랜 인증한 챌린지도 삭제했었음..)
-> 변경사항으로 감정키워드까지만 삭제되도록 수정하였습니다.
추가로, 챌린지 홈 조회 API에서 일기 존재 여부를 통해서 챌린지를 조회하도록 하고 있어서 무관하게 조회하도록 수정까지 하였습니다.
- 간단한 작업인데 로컬에서 Flask 띄워서 직접 분석도 실행해보다가 오래 걸렸습니다.. (MySQL 포트 3307로 바뀐거 등등 때문에..) 🥲
- 챌린지 홈 조회 API
로그를 봐버렸어..
1. 세팅 결과
일기
감정키워드
챌린지
2. 일기 삭제 API 실행
3. 삭제 결과
4. (1~3의 상태에서 진행) 기존 챌린지 홈 조회 API (감정 X / 챌린지 X)
5. (1~3의 상태에서 진행) 변경된 챌린지 홈 조회 API (감정 X / 챌린지 O)

[#299] Refactor: 일기 삭제 시, 사용자 챌린지는 삭제되지 않도록 수정

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/repository/CreditHistoryRepository.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/util/CreditUtil.java
src/main/java/umc/GrowIT/Server/util/dto/CreditGrantResult.java

User에 첫일기 작성여부 필드 추가 등 다른 방법도 존재하겠지만
당장에는 `CreditHistory` 테이블 조회가 가장 빠른 구현이 가능하여 이렇게 구현하였습니다.
(하지만, 5크레딧 제공하는 경우는 각 사용자별로 앱에서 단 1번만 발생함에도 불구하고 일기 작성시마다 회원가입 후 첫일기 작성인가?를 판단하는 쿼리가 발생하는 문제가 존재합니다)
보니까 약관쪽에 변경사항이 있고, 기존 DB를 날리지 않고 반영하기 위해서 table.sql이 config에 추가된 거 같습니다.
그런데 data.sql에는 제대로 최신화가 되지 않고 누락된 내용이 있어서 수정하였습니다.
※ 서므모듈 설정 관련
서브모듈 설정한 이유는 내부적으로는 공유되어야 하지만, 외부적으로는 드러나면 안되는 파일들 관리/공유를 원활하게 하기 위해 설정하였습니다.
그런데 `data.sql` & `table.sql` 이렇게 별도로 관리되다보니 위의 상황이 발생한거 같습니다.
DB를 결국에 초기화 or 새롭게 생성 후에 기본 데이터 세팅이 필요하다보니까 `data.sql` 관리가 중요합니다. 신경써주시면 감사하겠습니다!!
1. 앱 자체 첫일기 작성
2. 일기 삭제 후 재작성
3. 그 후, 다른 날짜 일기 첫작성
4. 일기 삭제 후 재작성

[#330] Feat: 앱 자체 일기 첫작성 시 제공되는 크레딧 구분

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/service/challengeService/ChallengeCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/util/CreditUtil.java

CreditGrantResult 생성에 따른 챌린지 응답 수정
```java
@Getter
@AllArgsConstructor
public class CreditGrantResult {
private final boolean granted;   // 크레딧 지급 여부
private final int amount;        // 실제 지급된 크레딧 수
}
``` 
1. ChallengeConverter에서 `boolean creditGranted, int creditAmount` 으로 선언하던 부분을 `CreditGrantResult result` 으로 변경함에 따라 크레딧 응답 부분도 일기와 동일하게 `result.isGranted()`, `result.getAmount()` 식으로 수정
2. `CHALLENGE_CREDIT` 상수는 `CreditUtil`에서 관리, 따라서
- 챌린지 인증 3개까지는 `CreditGrantResult(true, CHALLENGE_CREDIT)` 반환
- 챌린지 인증 4번째부터는 `CreditGrantResult(false, 0)` 반환
놉
1. 챌린지 인증 3개까지 크레딧 지급
2. 챌린지 인증 4번째부터 크레딧 지급 x

[#334] Refactor: CreditGrantResult 생성에 따른 챌린지 응답 수정

---

src/main/java/umc/GrowIT/Server/converter/ChallengeConverter.java
src/main/java/umc/GrowIT/Server/web/dto/ChallengeDTO/ChallengeResponseDTO.java

챌린지 현황 조회 시 챌린지 내용(content)을 반환하여,
챌린지 인증 작성 시 프론트측에서 챌린지의 내용까지 조회할 수 있도록 작업하였습니다.
그 외.. db값에 맞게 example 수정.. 그리고 n+1 문제 발생에 대한 고민...

[#369] Refactor: 챌린지 현황 조회 시 챌린지 내용 반환

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/repository/DiaryRepository.java
src/main/java/umc/GrowIT/Server/scheduler/Scheduler.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandService.java
src/main/java/umc/GrowIT/Server/service/diaryService/DiaryCommandServiceImpl.java
src/main/java/umc/GrowIT/Server/web/controller/DiaryController.java
src/main/java/umc/GrowIT/Server/web/controller/specification/DiarySpecification.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryRequestDTO.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

승현님과 파트를 나누어서 작업 진행하였습니다. #381 
- 동일 날짜에 작성한 일기 존재하는지 체크할 때에 `COMPLETED` 조건 추가
- 일기 저장 시, `PENDING` + `TEXT` or `VOICE` 추가 저장
- 크레딧 제공 & 기록 코드 삭제
(그 외, 메소드, dto 등 자잘한 것들 수정하였습니다)
스케줄러를 통해 `PENDING`일기 삭제 진행
X
X

[#388] Refactor: 기존 일기 저장 API 임시저장으로 변경

---

src/main/java/umc/GrowIT/Server/converter/DiaryConverter.java
src/main/java/umc/GrowIT/Server/web/dto/DiaryDTO/DiaryResponseDTO.java

음성일기 임시저장 시 일기내용을 반환합니다.
일기 분석 api 응답에 일기내용이 반환되고 있지 않으며, 음성일기 작성 시 요약&수정 작업이 필요하다는 프론트 측의 연락을 받고 수정 작업하게 되었습니다!
x
x

[#392] Refactor: 음성일기 임시저장 시 일기내용 반환

---

src/main/java/umc/GrowIT/Server/repository/DiaryRepository.java

일기 상태 PENDING, COMPLETED 추가 이후
일기가 PENDING 상태임에도 챌린지 홈에서 일기의 감정키워드가 조회되는 문제가 발생
-> 쿼리문에 COMPLETED 조건 추가하였습니다.
챌린지 리포트의 "마지막 일기 작성 날짜 조회" 쿼리문에도 COMPLETED 조건 추가하였습니다.
x
x

[#398] Fix: 챌린지 홈에서 일기 데이터 조회 시 COMPLETED 조건 추가
